# Generated by Django 2.2.5 on 2019-09-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0128_auto_20190925_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_multiple',
            name='name',
        ),
    ]
